// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYfyWCfI9i8i_2FiScS1b6CH8JF7eeBQ',
    appId: '1:195895174275:web:a7f2c26a4d3f61949da7b6',
    messagingSenderId: '195895174275',
    projectId: 'rmarket-22342',
    authDomain: 'rmarket-22342.firebaseapp.com',
    storageBucket: 'rmarket-22342.appspot.com',
    measurementId: 'G-ZTHRZWR8QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh9sVFThap8AHxLhwDeu0QZqa6NjBZVHo',
    appId: '1:195895174275:android:6323c542f46276aa9da7b6',
    messagingSenderId: '195895174275',
    projectId: 'rmarket-22342',
    storageBucket: 'rmarket-22342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNPxzUJAHxbPU4q6Ot6tQM-KJIZv-kLc',
    appId: '1:195895174275:ios:8961ad4b0513a3f29da7b6',
    messagingSenderId: '195895174275',
    projectId: 'rmarket-22342',
    storageBucket: 'rmarket-22342.appspot.com',
    iosClientId: '195895174275-q0i6a6g33vas41ottf2n04cnbm1t6csv.apps.googleusercontent.com',
    iosBundleId: 'com.example.rMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXNPxzUJAHxbPU4q6Ot6tQM-KJIZv-kLc',
    appId: '1:195895174275:ios:8961ad4b0513a3f29da7b6',
    messagingSenderId: '195895174275',
    projectId: 'rmarket-22342',
    storageBucket: 'rmarket-22342.appspot.com',
    iosClientId: '195895174275-q0i6a6g33vas41ottf2n04cnbm1t6csv.apps.googleusercontent.com',
    iosBundleId: 'com.example.rMarket',
  );
}
